server:
#  port: 0
  port: 8090
spring:
  application:
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
  datasource:
    #    url: jdbc:mysql://120.26.177.51:3306/user-center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/user-center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      #      username: root
      #      password: abc.123
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        #        server-addr: 120.26.177.51:8848
        server-addr: localhost:8848
        #        namespace: ef32c1be-c63c-4db4-8b07-b3b84a7c27ef

        metadata:
          instance: cc
          version: 1.0
          author: tt

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
#rocketmq:
#  name-server: 47.111.64.183:9876
#  name-server: 120.26.177.51:9876

jwt:
  secret: aaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccdddddaaaaaaabbbbbbcccccddddd
  expire-time-in-second: 123456
