server:
  port: 8083
spring:
  application:
    name: content-center
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
  main:
    allow-bean-definition-overriding: true

  datasource:
    #    url: jdbc:mysql://120.26.177.51:3306/content-center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/content-center?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    hikari:
      #      username: root
      #      password: abc.123
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    #        server-addr: 120.26.177.51:8848
    #        namespace: ef32c1be-c63c-4db4-8b07-b3b84a7c27ef
    sentinel:
      transport:
        dashboard: localhost:8080


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    com.soft1851.content.feignclient.UserCenterFeignClient: debug
feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full
        requestInterceptors:
          - com.soft1851.content.feignclient.TokenInterceptor
#      user-center:
#        loggerLevel: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50

rocketmq:
  name-server: 47.111.64.183:9876
#  name-server: 120.26.177.51:9876
  producer:
    group: test-group